### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by giannissc** [voneiden/cq-cam#17]
Hello there,

I have recently started using cq_cam and I am quite enjoying and I would love to help it develop further.
I have already fixed a bug that I found locally but documentation is lacking so I am not sure if the way I do it is the best. If you are willing to walk me through the code I am happy to update the documentation and fix any bugs that I find

Best wishes,
John

**Comment by voneiden** [comment]
Hi John, thanks for the comment! The intent is there but for the time being this one stays on my backlog.  You might also be interested in [fluent-experiments](https://github.com/voneiden/cq-cam/tree/fluent-experiments) branch which has a CQ like experimental fluent API and various experiments leveraging OpenCascade algorithms. I worked on this during last summer (northern hemisphere..), unfortunately I ran out of vacation before I could finish anything. I did use fluent-experiments to do some machining though, also last summer, so it's proven to work with some caveats. 

If you have small fixes, you're welcome to open PR's and I can take a look. Just keep in mind that sooner or later I do intend to do some heavy handed refactoring/rewriting to get this project stabilized, so you might not want to put too much effort here yet.

I do have hopes that I'll manage to do that during the upcoming summer season. 

Also, btw I'll convert this to a discussion.
