### ISSUE TITLE
visualize_job does not work unless you use cq_editor

### ISSUE THREAD

**Issue by giannissc** [voneiden/cq-cam#23]
I have recently switched from cq_editor to ocp_cad_viewer extension for vs code. Running visualize_job does not work but visualize_job_as_edges does

**Comment by voneiden** [comment]
It may very well be that AIS based rendering requires changes to ocp_cad_viewer like it required for cq-editor ( https://github.com/CadQuery/CQ-editor/pull/317 ). For cq-editor these changes were pretty simple.

**Comment by voneiden** [comment]
We can also research on our end if the edge based visualization could be improved (support different colours and arrows)

**Comment by voneiden** [comment]
Preliminary testing shows that render performance is actually slightly better with 100k random lines using `TopoDS_Edge` rather than `AIS_Line`.

It is slightly slower to generate Edges though. 

However there doesn't seem to be any easy way of configuring the color of an edge in OpenCASCADE

**Comment by voneiden** [comment]
Fixed by #31 - opened #36 for making the visualization more informative in ocp-vscode.
