### ISSUE TITLE
Precision in edge interpolation and offsetting

### ISSUE THREAD

**Issue by voneiden** [voneiden/cq-cam#44]
Currently hardcoded, should respect Job.precision

**Comment by giannissc** [comment]
Precision is also related to the units selected so maybe we could consolidate them?

**Comment by voneiden** [comment]
Yeah, that can be a separate issue. The current default of 3 decimals is 0.001" or 0.001 mm depending on the unit. For metric it's probably a bit excessive for a default. For imperial it's probably pretty good.

**Comment by voneiden** [comment]
#47
